CREATE TABLE TB_FORNECEDOR (
  CD_FORNECEDOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CNPJ_FORNECEDOR INT NULL,
  NOME_FORNECEDOR VARCHAR(255) NULL,
  PRIMARY KEY(CD_FORNECEDOR)
);

CREATE TABLE TB_COMPRA (
  CD_PRODUTO INT NOT NULL AUTO_INCREMENT,
  CD_FORNECEDOR INT NULL,
  DATA_COMPRA DATE NULL,
  HORA_COMPRA TIME NULL,
  PRIMARY KEY(CD_PRODUTO)
);

CREATE TABLE TB_CLIENTE (
  CPF_CLIENTE INT NOT NULL,
  CD_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NOME_CLIENTE VARCHAR(255) NULL,
  PRIMARY KEY(CPF_CLIENTE, CD_CLIENTE)
);

CREATE TABLE TB_VENDA (
  CD_PRODUTO INT NOT NULL AUTO_INCREMENT,
  TB_CLIENTE_CPF_CLIENTE INT NOT NULL,
  CD_CLIENTE INT NOT NULL,
  TB_CLIENTE_CD_CLIENTE INT NOT NULL,
  QTDE INT NULL,
  DATA_VENDA DATE NULL,
  HORA INTEGER UNSIGNED NULL,
  PRIMARY KEY(CD_PRODUTO, TB_CLIENTE_CPF_CLIENTE, CD_CLIENTE, TB_CLIENTE_CD_CLIENTE),
  INDEX TB_VENDA_FKIndex1(TB_CLIENTE_CPF_CLIENTE, TB_CLIENTE_CD_CLIENTE),
  FOREIGN KEY(TB_CLIENTE_CPF_CLIENTE, TB_CLIENTE_CD_CLIENTE)
    REFERENCES TB_CLIENTE(CPF_CLIENTE, CD_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TB_PRODUTO (
  CD_PRODUTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TB_VENDA_TB_CLIENTE_CD_CLIENTE INT NOT NULL,
  TB_VENDA_CD_CLIENTE INT NOT NULL,
  TB_VENDA_TB_CLIENTE_CPF_CLIENTE INT NOT NULL,
  TB_FORNECEDOR_CD_FORNECEDOR INTEGER UNSIGNED NOT NULL,
  TB_COMPRA_CD_PRODUTO INT NOT NULL,
  TB_VENDA_CD_PRODUTO INT NOT NULL,
  DESCRICAO_PRODUTO VARCHAR(255) NULL,
  TIPO_PRODUTO VARCHAR(20) NULL,
  NOME_PRODUTO VARCHAR(45) NULL,
  FORNECEDOR VARCHAR(255) NULL,
  FLAG_PRODUTO_ENTRADA VARCHAR(20) NULL,
  FLAG_PRODUTO_SAIDA INTEGER UNSIGNED NULL,
  CD_FORNECEDOR INTEGER UNSIGNED NULL,
  DT_INCLUSAO DATE NULL,
  DT_VALIDADE DATE NULL,
  DT_EXPIRACAO DATE NULL,
  HORA_EXPIRACAO TIME NULL,
  PRIMARY KEY(CD_PRODUTO),
  INDEX TB_PRODUTO_FKIndex1(TB_VENDA_CD_PRODUTO, TB_VENDA_TB_CLIENTE_CPF_CLIENTE, TB_VENDA_CD_CLIENTE, TB_VENDA_TB_CLIENTE_CD_CLIENTE),
  INDEX TB_PRODUTO_FKIndex2(TB_COMPRA_CD_PRODUTO),
  INDEX TB_PRODUTO_FKIndex3(TB_FORNECEDOR_CD_FORNECEDOR),
  FOREIGN KEY(TB_VENDA_CD_PRODUTO, TB_VENDA_TB_CLIENTE_CPF_CLIENTE, TB_VENDA_CD_CLIENTE, TB_VENDA_TB_CLIENTE_CD_CLIENTE)
    REFERENCES TB_VENDA(CD_PRODUTO, TB_CLIENTE_CPF_CLIENTE, CD_CLIENTE, TB_CLIENTE_CD_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_COMPRA_CD_PRODUTO)
    REFERENCES TB_COMPRA(CD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_FORNECEDOR_CD_FORNECEDOR)
    REFERENCES TB_FORNECEDOR(CD_FORNECEDOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TB_FILME (
  CD_PRODUTO INT NOT NULL AUTO_INCREMENT,
  TB_PRODUTO_CD_PRODUTO INTEGER UNSIGNED NOT NULL,
  DS_FILME VARCHAR(255) NULL,
  CD_SALA INT NULL,
  DATA_SESSAO DATE NULL,
  HORA_SESSAO TIME NULL,
  POLTRONA VARCHAR(20) NULL,
  CD_ESTAB INTEGER UNSIGNED NULL,
  PRIMARY KEY(CD_PRODUTO),
  INDEX TB_FILME_FKIndex1(TB_PRODUTO_CD_PRODUTO),
  FOREIGN KEY(TB_PRODUTO_CD_PRODUTO)
    REFERENCES TB_PRODUTO(CD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TB_ESTABELECIMENTO (
  CD_ESTABELECIMENTO INT NOT NULL AUTO_INCREMENT,
  TB_FILME_CD_PRODUTO INT NOT NULL,
  LOGRADOURO VARCHAR(255) NULL,
  PRIMARY KEY(CD_ESTABELECIMENTO),
  INDEX TB_ESTABELECIMENTO_FKIndex1(TB_FILME_CD_PRODUTO),
  FOREIGN KEY(TB_FILME_CD_PRODUTO)
    REFERENCES TB_FILME(CD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TB_ENDERECO (
  CD_FORNECEDOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TB_ESTABELECIMENTO_CD_ESTABELECIMENTO INT NOT NULL,
  TB_CLIENTE_CD_CLIENTE INT NOT NULL,
  TB_FORNECEDOR_CD_FORNECEDOR INTEGER UNSIGNED NOT NULL,
  TB_CLIENTE_CPF_CLIENTE INT NOT NULL,
  CD_CLIENTE INTEGER UNSIGNED NULL,
  CD_ESTABELECIMENTO INTEGER UNSIGNED NULL,
  DS_LOGRADOURO VARCHAR(255) NULL,
  DS_NUMERO VARCHAR(20) NULL,
  DS_COMPLEMENTO INTEGER UNSIGNED NULL,
  DS_BAIRRO VARCHAR(255) NULL,
  DS_CIDADE VARCHAR(255) NULL,
  DS_ESTADO VARCHAR(20) NULL,
  DS_MUNICIPIO VARCHAR(255) NULL,
  CEP NUMERIC NULL,
  TP_LOGRADOURO VARCHAR(50) NULL,
  PRIMARY KEY(CD_FORNECEDOR, TB_CLIENTE_CD_CLIENTE, TB_CLIENTE_CPF_CLIENTE),
  INDEX TB_ENDERECO_FKIndex1(TB_CLIENTE_CPF_CLIENTE, TB_CLIENTE_CD_CLIENTE),
  INDEX TB_ENDERECO_FKIndex2(TB_FORNECEDOR_CD_FORNECEDOR),
  INDEX TB_ENDERECO_FKIndex3(TB_ESTABELECIMENTO_CD_ESTABELECIMENTO),
  FOREIGN KEY(TB_CLIENTE_CPF_CLIENTE, TB_CLIENTE_CD_CLIENTE)
    REFERENCES TB_CLIENTE(CPF_CLIENTE, CD_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_FORNECEDOR_CD_FORNECEDOR)
    REFERENCES TB_FORNECEDOR(CD_FORNECEDOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_ESTABELECIMENTO_CD_ESTABELECIMENTO)
    REFERENCES TB_ESTABELECIMENTO(CD_ESTABELECIMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TB_CONTATO (
  CD_ESTABELECIMENTO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TB_COMPRA_CD_PRODUTO INT NOT NULL,
  TB_FORNECEDOR_CD_FORNECEDOR INTEGER UNSIGNED NOT NULL,
  TB_CLIENTE_CD_CLIENTE INT NOT NULL,
  TB_CLIENTE_CPF_CLIENTE INT NOT NULL,
  TB_ESTABELECIMENTO_CD_ESTABELECIMENTO INT NOT NULL,
  CD_FORNECEDOR INTEGER UNSIGNED NULL,
  CD_CLIENTE INTEGER UNSIGNED NULL,
  FLAG_TP_CONTATO VARCHAR(20) NULL,
  E-MAIL VARCHAR(255) NULL,
  CD_DDD1 NUMERIC NULL,
  CD_TELEFONE 1 NUMERIC NULL,
  CD_DDD2 NUMERIC NULL,
  CD_TELEFONE2 NUMERIC NULL,
  CD_DDD3 NUMERIC NULL,
  CD_TELEFONE3 NUMERIC NULL,
  PRIMARY KEY(CD_ESTABELECIMENTO, TB_COMPRA_CD_PRODUTO, TB_CLIENTE_CD_CLIENTE, TB_CLIENTE_CPF_CLIENTE),
  INDEX TB_CONTATO_FKIndex1(TB_ESTABELECIMENTO_CD_ESTABELECIMENTO),
  INDEX TB_CONTATO_FKIndex2(TB_CLIENTE_CPF_CLIENTE, TB_CLIENTE_CD_CLIENTE),
  INDEX TB_CONTATO_FKIndex3(TB_FORNECEDOR_CD_FORNECEDOR),
  INDEX TB_CONTATO_FKIndex4(TB_COMPRA_CD_PRODUTO),
  FOREIGN KEY(TB_ESTABELECIMENTO_CD_ESTABELECIMENTO)
    REFERENCES TB_ESTABELECIMENTO(CD_ESTABELECIMENTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_CLIENTE_CPF_CLIENTE, TB_CLIENTE_CD_CLIENTE)
    REFERENCES TB_CLIENTE(CPF_CLIENTE, CD_CLIENTE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_FORNECEDOR_CD_FORNECEDOR)
    REFERENCES TB_FORNECEDOR(CD_FORNECEDOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TB_COMPRA_CD_PRODUTO)
    REFERENCES TB_COMPRA(CD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE TB_SALA (
  CD_SALA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TB_FILME_CD_PRODUTO INT NOT NULL,
  DS_TIPO_SALA VARCHAR(50) NULL,
  LOTACAO INT NULL,
  NUMERO_SALA INT NULL,
  TIPO_POLTRONA INTEGER UNSIGNED NULL,
  PRIMARY KEY(CD_SALA, TB_FILME_CD_PRODUTO),
  INDEX TB_SALA_FKIndex1(TB_FILME_CD_PRODUTO),
  FOREIGN KEY(TB_FILME_CD_PRODUTO)
    REFERENCES TB_FILME(CD_PRODUTO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


